spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.229.203:3306/web_admin?serverTimezone=UTC
    username: root
    password: 123123cc

    druid:
      aop-patterns: com.chris.webdamin.*

